version: "3.3"
services: 
    sql:
        image: "mysql:latest"
        environment:
            - MYSQL_ROOT_PASSWORD=gueban
        ports:
            - 2801:3306
        volumes:
            - "sql-vol:/var/lib/mysql"
        networks:
            - gueban-network
    cache:
        image: "redis:alpine"
        ports:
            - 5200:6379
        volumes:
            - "cache-vol:/data"
        networks:
            - gueban-network
    backend: 
        image: miguesteban/aguita-python:latest
        secrets:
            - secret-u
            - secret-p
        environment:
            - MYSQLUSER=/run/secrets/secret-u
            - MYSQLPASSWORD=/run/secrets/secret-p
            - MYSQLHOST=YOUR_PUBLIC_IP
            - MYSQLPORT=2801
            - MYSQLDB=project
            - REDISHOST=YOUR_PUBLIC_IP
            - REDISPORT=5200
        network_mode: host
    web:
        image: miguesteban/front
        network_mode: host
secrets:
    secret-u:
        file: ./backend/secret-u.txt
    secret-p:
        file: ./backend/secret-p.txt
volumes:
    sql-vol:
    cache-vol:
networks:
    gueban-network:
        driver: bridge